spring:
  profiles:
    active: dev



#spring:
#  profiles:
#    active: dev, prod
# second way 2


#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://spingproject90871536:Punr45mCuCOVF9abc9b@cluster0.tdfnqqjo.mongodb.net/?retryWrites=true&w=majority&apnapName=Cluster0
#      database: journaldb
#      auto-index-creation: true
#
#server:
#  port: 8080
#  servlet:
#    context-path: /journal
