spring:
  data:
    mongodb:
      uri: mongodb+srv://spingproject90871435:Punr5mCuCOVF9abc9b@cluster0.tcnqqjo.mongodb.net/?retryWrites=true&w=majority&apnapName=Cluster0
      database: journaldb
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /journal
